fixing zshrc

diff --git a/dotzshrc b/dotzshrc
--- a/dotzshrc
+++ b/dotzshrc
@@ -1,235 +1,177 @@
-# If you come from bash you might have to change your $PATH.
+zmodload zsh/zprof
+
+# ==========================================
+# 1. SYSTEM PATHS & ENVIRONMENT ARCHITECTURE
+# ==========================================
+export SHELL=/bin/zsh
 export PATH=$HOME/.bin:$PATH
 
-# Path to your oh-my-zsh installation.
-export ZSH=$HOME/.oh-my-zsh
-
+# Detect architecture: arm64 = Apple Silicon, x86_64 = Rosetta / Intel
 UNAME_MACHINE="$(/usr/bin/uname -m)"
-
-if [[ "${UNAME_MACHINE}" == "arm64" ]]
-then
-  # On ARM macOS, this script installs to /opt/homebrew only
+if [[ "${UNAME_MACHINE}" == "arm64" ]]; then
   eval "$(/opt/homebrew/bin/brew shellenv)"
-elif [[ "${UNAME_MACHINE}" == "x86_64" ]]
-then
-  # On Intel macOS, this script installs to /usr/local only
+elif [[ "${UNAME_MACHINE}" == "x86_64" ]]; then
   eval "$(/usr/local/bin/brew shellenv)"
 fi
 
+# Additional explicit paths (Apple Silicon hardening)
+export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
+export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
 
-# Set name of the theme to load --- if set to "random", it will
-# load a random theme each time oh-my-zsh is loaded, in which case,
-# to know which specific one was loaded, run: echo $RANDOM_THEME
-# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
+# ==========================================
+# 2. EARLY NVM GUARD FLAGS (Must sit above plugins)
+# ==========================================
+export ZSH_NVM_LAZY_LOAD=true
+export ZSH_NVM_AUTO_USE=true
+
+# ==========================================
+# 3. OH MY ZSH FRAMEWORK CORE CONFIGURATION
+# ==========================================
 ZSH_THEME="muse"
+export ZSH=$HOME/.oh-my-zsh
 
-# Set list of themes to pick from when loading at random
-# Setting this variable when ZSH_THEME=random will cause zsh to load
-# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
-# If set to an empty array, this variable will have no effect.
-
-# Uncomment the following line to use case-sensitive completion.
-# CASE_SENSITIVE="true"
-
-# Uncomment the following line to use hyphen-insensitive completion.
-# Case-sensitive completion must be off. _ and - will be interchangeable.
-# HYPHEN_INSENSITIVE="true"
-
-# Uncomment the following line to disable bi-weekly auto-update checks.
-# DISABLE_AUTO_UPDATE="true"
-
-# Uncomment the following line to automatically update without prompting.
-# DISABLE_UPDATE_PROMPT="true"
-
-# Uncomment the following line to change how often to auto-update (in days).
-# export UPDATE_ZSH_DAYS=13
-
-# Uncomment the following line if pasting URLs and other text is messed up.
-# DISABLE_MAGIC_FUNCTIONS=true
-
-# Uncomment the following line to disable colors in ls.
-# DISABLE_LS_COLORS="true"
-
-# Uncomment the following line to disable auto-setting terminal title.
-# DISABLE_AUTO_TITLE="true"
-
-# Uncomment the following line to enable command auto-correction.
-# ENABLE_CORRECTION="true"
-
-# Uncomment the following line to display red dots whilst waiting for completion.
-# COMPLETION_WAITING_DOTS="true"
-
-# Uncomment the following line if you want to disable marking untracked files
-# under VCS as dirty. This makes repository status check for large repositories
-# much, much faster.
-# DISABLE_UNTRACKED_FILES_DIRTY="true"
-
-# Uncomment the following line if you want to change the command execution time
-# stamp shown in the history command output.
-# You can set one of the optional three formats:
-# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
-# or set a custom format using the strftime function format specifications,
-# see 'man strftime' for details.
-# HIST_STAMPS="mm/dd/yyyy"
-
-# Would you like to use another custom folder than $ZSH/custom?
-# ZSH_CUSTOM=/path/to/new-custom-folder
-
-# Which plugins would you like to load?
-# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
-# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
-# Example format: plugins=(rails git textmate ruby lighthouse)
-# Add wisely, as too many plugins slow down shell startup.
 plugins=(
-  git
-  dotenv
-  macos
-  brew
-  celery
-  colorize
-  docker
-  fzf
-  fzf-tab
-  gulp
-  iterm2
-  nvm
-  npm
-  pip
-  pylint
-  python
-  supervisor
-  textmate
-  virtualenv
-  vscode
-  yarn
-  zsh-nvm
-  zsh-syntax-highlighting
-  zsh-autosuggestions
+  git dotenv macos brew celery colorize docker fzf fzf-tab
+  gulp iterm2 npm pip pylint python supervisor textmate
+  virtualenv vscode yarn zsh-nvm zsh-autosuggestions zsh-syntax-highlighting
 )
-if type brew &>/dev/null; then
-    export FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
-    autoload -Uz compinit
-    compinit
-fi
+
 [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
 source $ZSH/oh-my-zsh.sh
 
-# User configuration
-
-# export MANPATH="/usr/local/man:$MANPATH"
-
-# You may need to manually set your language environment
-# export LANG=en_US.UTF-8
-
-# Preferred editor for local and remote sessions
- if [[ -n $SSH_CONNECTION ]]; then
-   export EDITOR='vim'
- else
-   export EDITOR='subl'
- fi
-
-# Compilation flags
-# export ARCHFLAGS="-arch x86_64"
-
-# Set personal aliases, overriding those provided by oh-my-zsh libs,
-# plugins, and themes. Aliases can be placed here, though oh-my-zsh
-# users are encouraged to define aliases within the ZSH_CUSTOM folder.
-# For a full list of active aliases, run `alias`.
-#
-# Example aliases
-# alias zshconfig="mate ~/.zshrc"
-# alias ohmyzsh="mate ~/.oh-my-zsh"
-if [[ -n $VIRTUAL_ENV && -e "${VIRTUAL_ENV}/bin/activate" ]]; then
-  source "${VIRTUAL_ENV}/bin/activate"
-fi
-export P4CONFIG=".perforce"
-export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
-[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
-[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
-export PATH="${PATH}:${NVM_BIN}"
+# ==========================================
+# 4. CORE APP ENVIRONMENTS & REPO MANAGEMENT
+# ==========================================
 export NODE_ENV="development"
 export NODE_PORT=5000
 export AIRFLOW_HOME=$HOME/work/airflow_workflow
 export ACKRC=$HOME/.ackrc
-export PATH="$PATH:$HOME/jetbrains_shell_scripts"
 export GIT_SSH=/usr/bin/ssh
-#alias git="hub"
 export DJANGO_READ_DOT_ENV_FILE=true
-export PATH="$PATH:/usr/local/lib/ruby/gems/2.6.0:/usr/local/Cellar/ruby/2.6.4_2/lib/ruby/gems/2.6.0"
-alias runtest="./manage.py test -- -s -r fEps --cov=. --cov-report=html --cov-config=.coveragerc"
+export P4CONFIG=".perforce"
 
-# NVM script
-# place this after nvm initialization!
-autoload -U add-zsh-hook
-load-nvmrc() {
-  local node_version="$(nvm version)"
-  local nvmrc_path="$(nvm_find_nvmrc)"
-
-  if [ -n "$nvmrc_path" ]; then
-    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")
-
-    if [ "$nvmrc_node_version" = "N/A" ]; then
-      nvm install
-    elif [ "$nvmrc_node_version" != "$node_version" ]; then
-      nvm use
-    fi
-  elif [ "$node_version" != "$(nvm version default)" ]; then
-    echo "Reverting to nvm default version"
-    nvm use default
-  fi
-}
-add-zsh-hook chpwd load-nvmrc
-load-nvmrc
-
-test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
-alias clearpath="typeset -aU path"
-export GIT_SSH=/usr/bin/ssh
-alias portainer="docker run -d -p 8090:8000 -p 9090:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer"
-export PATH="/usr/local/opt/ruby/bin:$PATH"
-export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
-export PATH=$HOME/.gem/ruby/2.7.0/bin:$PATH
-export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
-export M2_HOME="/usr/local/opt/maven"
-export PATH="/usr/local/opt/maven/bin:$PATH"
-export PATH=$HOME/.local/bin:$PATH
-export PATH="/usr/local/opt:$PATH"
-alias fp="/Applications/Firefox.app/Contents/MacOS/firefox-bin -P > /dev/null 2>&1 &"
-alias vv="source venv/bin/activate"
-export PATH="/Users/Shared/DBngin/mysql/8.0.19/bin:$PATH"
-ckill () {
-    ps -ef | grep "celery" | \
-    awk '{print $2}' | \
-    xargs kill -9
-}
-export FZF_BASE=$HOME/.fzf
-alias cdb="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222 &"
-eval "$(rbenv init -)"
-eval "$(jenv init -)"
+# ==========================================
+# 5. CORE ENVIRONMENT TOOL INTEGRATIONS (rbenv, jenv, direnv)
+# Guarded with command -v so missing tools don't error out
+# ==========================================
+command -v rbenv  &>/dev/null && eval "$(rbenv init -)"
 export PATH="$HOME/.jenv/bin:$PATH"
-export CFLAGS="-I$(brew --prefix openssl)/include -I$(brew --prefix bzip2)/include -I$(brew --prefix readline)/include -I$(xcrun --show-sdk-path)/usr/include"
-export LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix readline)/lib -L$(brew --prefix zlib)/lib -L$(brew --prefix bzip2)/lib"
-export CPPFLAGS="-I/usr/local/opt/zlib/include -I/usr/local/opt/bzip2/include"
-export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"
-export PATH="$HOME/.pyenv/bin:$PATH"
-eval "$(pyenv init --path)"
-eval "$(direnv hook zsh)"
-alias hb_home="cd $(brew --prefix)"
-alias hb_binary="cd $(brew --prefix)/bin/"
-alias hb_cellar="cd $(brew --prefix)/Cellar/"
-alias hb_config="cd $(brew --prefix)/etc/"
-alias hb_logs="cd $(brew --prefix)/var/log"
-alias hb_opt="cd $(brew --prefix)/opt"
-export PATH="/usr/local/opt/go@1.16/bin:$PATH"
-export PATH="$PATH:/Users/lokesh.sanapalli/Library/Application Support/JetBrains/Toolbox/scripts"
-test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh" || true
-# Load pyenv automatically by appending
-# the following to
-# ~/.zprofile (for login shells)
-# and ~/.zshrc (for interactive shells) :
+command -v jenv   &>/dev/null && eval "$(jenv init -)"
+# command -v direnv &>/dev/null && eval "$(direnv hook zsh)"
 
+# ==========================================
+# 6. PYTHON ENVIRONMENT MANAGEMENT (pyenv)
+# ==========================================
 export PYENV_ROOT="$HOME/.pyenv"
 [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
-eval "$(pyenv init - zsh)"
+command -v pyenv &>/dev/null && eval "$(pyenv init --path)"
 
-# Restart your shell for the changes to take effect.
+# ==========================================
+# 7. SAFE SYSTEM TOOL PATH APPENDINGS
+# ==========================================
+export PATH="/usr/local/opt/ruby/bin:$PATH"
+export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
+export PATH="$HOME/.gem/ruby/2.7.0/bin:$PATH"
+export PATH="/usr/local/opt/maven/bin:$PATH"
+export PATH="$HOME/.local/bin:$PATH"
+export PATH="/usr/local/opt:$PATH"
+export PATH="/Users/Shared/DBngin/mysql/8.0.19/bin:$PATH"
 export PATH="/usr/local/opt/mariadb@10.6/bin:$PATH"
+export PATH="/Users/lokeshsanapalli/bin/apache-maven-3.9.15/bin:$PATH"
+export PATH="$PATH:$HOME/jetbrains_shell_scripts"
+export PATH="$PATH:/Users/lokesh.sanapalli/Library/Application Support/JetBrains/Toolbox/scripts"
+export PATH="$PATH:/usr/local/lib/ruby/gems/2.6.0:/usr/local/Cellar/ruby/2.6.4_2/lib/ruby/gems/2.6.0"
+
+export M2_HOME="/usr/local/opt/maven"
+
+# ==========================================
+# 8. COMPILER BUILD FLAGS & RUBY CONFIG
+# Deferred into a function — brew is reliably on PATH after oh-my-zsh init above
+# ==========================================
+_setup_build_flags() {
+  local hb sdk_path
+  if [[ "$UNAME_MACHINE" == "arm64" ]]; then
+    hb="/opt/homebrew/opt"
+  else
+    hb="/usr/local/opt"
+  fi
+  sdk_path="$(xcrun --show-sdk-path 2>/dev/null || echo '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk')"
+
+  export CFLAGS="-I${hb}/openssl/include -I${hb}/bzip2/include -I${hb}/readline/include -I${sdk_path}/usr/include"
+  export LDFLAGS="-L${hb}/openssl/lib -L${hb}/readline/lib -L${hb}/zlib/lib -L${hb}/bzip2/lib"
+  export CPPFLAGS="-I${hb}/zlib/include -I${hb}/bzip2/include"
+  export PKG_CONFIG_PATH="${hb}/zlib/lib/pkgconfig"
+  export RUBY_CONFIGURE_OPTS="--with-openssl-dir=${hb}/openssl@1.1"
+}
+_setup_build_flags
+
+# ==========================================
+# 9. USER FUNCTIONAL ALIASES & SCRIPTS
+# ==========================================
+alias runtest="./manage.py test -- -s -r fEps --cov=. --cov-report=html --cov-config=.coveragerc"
+alias clearpath="typeset -aU path"
+alias portainer="docker run -d -p 8090:8000 -p 9090:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer"
+alias fp="/Applications/Firefox.app/Contents/MacOS/firefox-bin -P > /dev/null 2>&1 &"
+alias vv="source venv/bin/activate"
+alias cdb="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222 &"
+
+# hb_* as functions (not aliases) so brew --prefix is evaluated at call time, not load time
+hb_home()   { cd "$(brew --prefix)"; }
+hb_binary() { cd "$(brew --prefix)/bin/"; }
+hb_cellar() { cd "$(brew --prefix)/Cellar/"; }
+hb_config() { cd "$(brew --prefix)/etc/"; }
+hb_logs()   { cd "$(brew --prefix)/var/log"; }
+hb_opt()    { cd "$(brew --prefix)/opt"; }
+
+# pgrep_kill: show matching processes, confirm, then kill
+# Usage: pgrep_kill <process-name>
+pgrep_kill() {
+  if [[ -z "$1" ]]; then
+    echo "Usage: pgrep_kill <process-name>"
+    return 1
+  fi
+
+  local name="$1"
+  local matches
+  matches=$(ps -eo pid,ppid,user,%cpu,%mem,stat,start,command | grep -i "$name" | grep -v grep | grep -v "pgrep_kill")
+
+  if [[ -z "$matches" ]]; then
+    echo "No processes found matching: $name"
+    return 0
+  fi
+
+  echo "\n\033[1mMatching processes:\033[0m"
+  echo "  PID   PPID USER             %CPU %MEM STAT STARTED COMMAND"
+  echo "$matches"
+  echo ""
+
+  local pids
+  pids=$(echo "$matches" | awk '{print $1}')
+  local pid_count
+  pid_count=$(echo "$pids" | wc -l | tr -d ' ')
+
+  echo "\033[33mAbout to kill $pid_count process(es) with SIGKILL (kill -9).\033[0m"
+  echo -n "Confirm? [y/N] "
+  read -r confirm
+
+  if [[ "$confirm" =~ ^[Yy]$ ]]; then
+    echo "$pids" | xargs kill -9 2>/dev/null
+    echo "\033[32mKilled $pid_count process(es) matching '$name'.\033[0m"
+  else
+    echo "Aborted."
+  fi
+}
+
+export FZF_BASE=$HOME/.fzf
+
+# ==========================================
+# 10. TERMINAL INTEGRATION WRAPPERS
+# ==========================================
+test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh" || true
+
+# ==========================================
+# 11. FAST NODE MANAGER ACTIVATION
+# ==========================================
+# command -v fnm &>/dev/null && eval "$(fnm env --use-on-cd)"
+
+# zprof
